apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole-http
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pihole-svc
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole-https
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pihole-svc
            port:
              number: 443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole-port53
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pihole-svc
            port:
              number: 53              
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole-port67
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pihole-svc
            port:
              number: 67              
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-svc
spec:
  ports:
    - port: 80
      protocol: TCP
      name: http
    - port: 443
      protocol: TCP
      name: https
    - port: 53
      protocol: TCP
      name: port53
    - port: 53
      protocol: UDP
      name: port53-udp      
    - port: 67
      protocol: UDP
      name: port67-udp
  selector:
    app:  pihole
