apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: dnsmasq-pvc
spec:
    accessModes:
        - ReadWriteMany
    storageClassName: longhorn
    resources:
        requests:
            storage: 100Mi
