apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: pihole
    name: pihole
    namespace: default
spec:
    selector:
        matchLabels:
            app: pihole
    template:
        metadata:
            labels:
                app: pihole
        spec:
            containers:
                - image: pihole/pihole:v5.0
                  imagePullPolicy: IfNotPresent
                  name: pihole
                  env:
                      - name: WEBPASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: pihole-secret
                                key: WEBPASSWORD
                      - name: TZ
                        valueFrom:
                            configMapKeyRef:
                                name: pihole-config
                                key: TZ
                      - name: DNS1
                        valueFrom:
                            configMapKeyRef:
                                name: pihole-config
                                key: DNS1
                      - name: DNS2
                        valueFrom:
                            configMapKeyRef:
                                name: pihole-config
                                key: DNS2
                  volumeMounts:
                      - name: pihole-pvc
                        mountPath: '/etc/pihole'
                      - name: dnsmasq-pvc
                        mountPath: '/etc/dnsmasq.d'
            restartPolicy: Always
            volumes:
                - name: pihole-pvc
                  persistentVolumeClaim:
                      claimName: pihole-pvc
                - name: dnsmasq-pvc
                  persistentVolumeClaim:
                      claimName: dnsmasq-pvc