apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-pvc-v1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi      


